UPDATE cleanup_authorities
SET phase = CASE phase
    WHEN 'RESERVED' THEN 'ACTIVE:RESERVED'
    WHEN 'STORAGE_ALLOCATED' THEN 'ACTIVE:STORAGE'
    WHEN 'WORKTREE_CREATED' THEN 'ACTIVE:WORKTREE'
    WHEN 'RUNTIME_CREATED' THEN 'ACTIVE:RUNTIME'
    WHEN 'PI_STARTED' THEN 'ACTIVE:PI_STARTED'
    WHEN 'RUNNING' THEN 'ACTIVE:RUNNING'
    WHEN 'REVIEW_READY' THEN 'RETAIN_REQUESTED'
    ELSE phase
END;

ALTER TABLE cleanup_authorities
    ADD CONSTRAINT cleanup_authorities_phase_check CHECK (phase IN (
        'ACTIVE:RESERVED',
        'ACTIVE:STORAGE',
        'ACTIVE:WORKTREE',
        'ACTIVE:RUNTIME',
        'ACTIVE:PI_STARTED',
        'ACTIVE:RUNNING',
        'ACTIVE:POST_PI_BEFORE_EVENT',
        'RETAIN_REQUESTED',
        'RETAINED',
        'CLEANUP_PENDING',
        'RUNTIME_STOPPED',
        'RUNTIME_DESTROYED',
        'GIT_RECOVERED_CLEANED',
        'STORAGE_RELEASED',
        'RESERVATION_RELEASED',
        'RESOLVED'
    ));
