[package]
name = "runtime-docker"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true

[lints]
workspace = true

[dependencies]
async-trait.workspace = true
bollard.workspace = true
chrono.workspace = true
execution-storage.workspace = true
futures-util.workspace = true
orchestrator-core.workspace = true
runtime-traits.workspace = true
tracing.workspace = true

[dev-dependencies]
runtime-apptainer.workspace = true
runtime-podman.workspace = true
serde_json.workspace = true
tempfile.workspace = true
tokio.workspace = true
